name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to WordPress SVN
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SVN
      run: sudo apt-get install -y subversion

    - name: Checkout WordPress.org SVN repo
      run: svn checkout https://plugins.svn.wordpress.org/fib-payments-gateway/ svn

    - name: Exclude unwanted files
      run: |
        # Remove unwanted files before syncing with SVN
        rm -f package-lock.json webpack.config.js phpcs.xml package.json .gitignore

    - name: Sync trunk with GitHub
      run: |
        # Clear out the SVN trunk directory
        rm -rf svn/trunk/*
        
        # Copy all files from GitHub repo into SVN trunk
        cp -R * svn/trunk/

        # Force add all files to SVN
        svn add --force svn/trunk/*

        # Remove any files in SVN that are deleted in GitHub
        svn status svn/trunk | grep '^!' | awk '{print $2}' | xargs svn delete || true

    - name: Tag version in SVN
      if: github.ref != ''
      run: |
        # Create a tag based on the GitHub version
        svn copy svn/trunk svn/tags/${GITHUB_REF_NAME}
        svn add svn/tags/${GITHUB_REF_NAME}

    - name: Commit changes to SVN
      env:
        SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
      run: |
        # Commit changes with the version tag
        svn commit -m "Deploy version ${GITHUB_REF_NAME}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache
