name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to WordPress SVN
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SVN
      run: sudo apt-get install -y subversion

    - name: Cleanup local SVN directory
      run: |
        # Remove any existing local SVN directory to avoid conflicts
        rm -rf svn

    - name: Checkout WordPress.org SVN repo
      run: svn checkout https://plugins.svn.wordpress.org/fib-payments-gateway/ svn
      
    - name: Sync trunk with GitHub
      run: |
        # Clear out the SVN trunk directory
        rm -rf svn/trunk/*
        
        # Copy all files from GitHub repo into SVN trunk, excluding the 'svn' directory and unwanted files
        rsync -av --exclude='svn' --exclude='package-lock.json' --exclude='webpack.config.js' --exclude='phpcs.xml' --exclude='package.json' --exclude='.gitignore' ./ svn/trunk/

        # Force add all files to SVN
        svn add --force svn/trunk/*

        # Remove any files in SVN that are deleted in GitHub
        svn status svn/trunk | grep '^!' | awk '{print $2}' | xargs svn delete || true

    - name: Tag version in SVN
      if: github.ref != ''
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        # Check if the tag already exists in the remote SVN repository
        if svn list https://plugins.svn.wordpress.org/fib-payments-gateway/tags/ | grep -q $VERSION; then
          echo "Tag $VERSION already exists in SVN. Skipping tag creation."
        else
          # Create the new tag
          echo "Tag $VERSION does not exist, creating new tag."
          svn copy svn/trunk svn/tags/$VERSION
        fi

    - name: Commit changes to SVN
      env:
        SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        svn commit svn/ -m "Deploy version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache
